#mysql service
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-db-service # host
  labels:
    app: drupal9
spec:
  type: NodePort
  ports:
  - name: drupal-db
    port: 3306
    targetPort: 3306
    nodePort: 31100
  selector:
    app: drupal-db
    tier: backend

#mysql deployment
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: drupal-db
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: drupal-db
  strategy:
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: drupal-db
        tier: backend
    spec:
      containers:
       - image: mariadb:latest
         name: drupal-mysql-cont
         resources:
           requests:
             memory: "64Mi"
             cpu: "250m"
           limits:
             memory: "128Mi"
             cpu: "500m"
         env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password  
         - name: MYSQL_DATABASE
           value: "drupal-database"       
         - name: MYSQL_USER
           value: "root" 
         ports:
         - containerPort: 3306
           name: drupal-mysql 
           protocol: TCP
         volumeMounts:
         - name: vol-drupal
           mountPath: /var/lib/drupal-mysql
           subPath: dbdata
      volumes:
      - name: vol-drupal
        persistentVolumeClaim:
          claimName: drupal-pvc-db