# drupal deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal9
  labels:
    app: drupal9
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal9
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal9
        tier: frontend
    spec:
      initContainers:
      - name: init-sites-volume
        image: drupal:9.2.5
        command: ['/bin/bash', '-c']
        args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']
        volumeMounts:
        - mountPath: /data
          name: drupal-persistent-storage
      containers:
      - image: drupal:9.2.5
        name: drupal9
        env:
        - name: DRUPAL_DATABASE_HOST
          value: "drupal-db-service"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DRUPAL_DATABASE_USER
          value: "root"
        - name: MYSQL_DATABASE
          value: "drupal-database"
        ports: 
        - containerPort: 80
          name: drupal9
        volumeMounts:
        - mountPath: /var/www/html/modules
          name: drupal-persistent-storage
          subPath: modules
        - mountPath: /var/www/html/profiles
          name: drupal-persistent-storage                 
          subPath: profiles
        - mountPath: /var/www/html/sites
          name: drupal-persistent-storage 
          subPath: sites
        - mountPath: /var/www/html/themes
          name: drupal-persistent-storage
          subPath: themes
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim: 
            claimName: drupal-pvc
          


        

# drupal service
---
apiVersion: v1
kind: Service
metadata:
  name: drupal9
  labels:
    app: drupal9
spec:
  selector:
    app: drupal9
    tier: frontend
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80  
    targetPort: 80
    nodePort: 31976
    
