apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc-mysql
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
