
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc-db
  labels:
    app: drupal9
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
